### PR TITLE
Add minimum blender version to readme

### LINKED ISSUE #9: Missing minimum blender version from readme
The plugin is only compatible with Blender version >=3.2.

This should be stated in the README file

### PR DESCRIPTION
**Pull request by itsFrank**
Add minimum blender version to readme

Fixes #9

### CODE REVIEW

**Review by Nightriff — APPROVED** [review]

**Comment by itsFrank** [comment]
Comment for CLA bot

**Comment by itsFrank** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cliffchapmanrbx** [comment]
Nice work!

**Comment by cliffchapmanrbx** [comment]
Nice work, thanks!

**Pull request merged**
